### ISSUE TITLE
fix(cli): 14.0.0-alpha.1 hangs when run

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/syncpack#253]
Moved discussion from [microsoft/FluidFramework#22146](https://github.com/microsoft/FluidFramework/pull/22146) to save on noise over there.

> Hey @tylerbutler, FYI there's an alpha preview of a Rust rewrite available at [14.0.0-alpha.1](https://github.com/JamieMason/syncpack/releases/tag/14.0.0-alpha.1) now. I've been developing it against the FluidFramework repository so you should hopefully be in a good starting point 🤞
>
> – https://github.com/microsoft/FluidFramework/pull/22146#issuecomment-2452154808

> @JamieMason I had a chance to try this today, and it seems to hang, at least with the config I have. You should be able to reproduce it on the [syncpack-config branch](https://github.com/tylerbutler/FluidFramework/tree/syncpack-config) on my fork. I'm happy to file an issue if it's helpful. Not sure what other info to collect.
>
> – https://github.com/microsoft/FluidFramework/pull/22146#issuecomment-2495207763

> Thanks @tylerbutler, which OS are you using?
>
> – https://github.com/microsoft/FluidFramework/pull/22146#issuecomment-2495490710

> @JamieMason I've tested on Ubuntu 20.04 and mac OS Sequoia ARM. Same behavior on both. I can try Windows 11 if it's helpful. I also tried node 18.20 and node 20.18 when I briefly forgot it was now written in rust. :) If you've been testing with this repo, would you mind sharing the config you've been testing with?
>
> – https://github.com/microsoft/FluidFramework/pull/22146#issuecomment-2504742037

**Comment by JamieMason** [comment]
Thanks a lot for digging into it some more.

My first hunch was Windows just because that's the OS I've not had access to yet. I then remembered you're on Node 16 in this repo and thought it might be that as I've only been running on Node 20.

In order to keep supporting .js and .ts config files [it still needs to have this bit of JS](https://github.com/JamieMason/syncpack/blob/2374a4607c067df65e8ba7a64a6078a475452bf8/npm/index.js) at least for the time being, so I thought it could be that. But if you've tried 18 and 20 I'm really not sure for the moment.

> If you've been testing with this repo, would you mind sharing the config you've been testing with?

I've been running it locally from [v14-alpha: /fixtures/fluid-framework](https://github.com/JamieMason/syncpack/tree/2374a4607c067df65e8ba7a64a6078a475452bf8/fixtures/fluid-framework) which is basically this repo with everything but files relevant to syncpack deleted. So the config file [`/fixtures/fluid-framework/syncpack.config.cjs`](https://github.com/JamieMason/syncpack/blob/2374a4607c067df65e8ba7a64a6078a475452bf8/fixtures/fluid-framework/syncpack.config.cjs) should be identical as of ~ Oct 30th.

Obviously I'd hold off on this alpha version, I thought it was further along than it is but I think it's better to wait.

Thanks again for your help, I'll have a look at your repro and see if I can figure out what's going on.

**Comment by JamieMason** [comment]
This should be fixed in [14.0.0-alpha.3](https://github.com/JamieMason/syncpack/releases/tag/14.0.0-alpha.3).

If you could give this a try and let me know @tylerbutler that would be a big help, thanks.

**Comment by tylerbutler** [comment]
> This should be fixed in [14.0.0-alpha.3](https://github.com/JamieMason/syncpack/releases/tag/14.0.0-alpha.3).
> 
> If you could give this a try and let me know [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/19589?s=64&amp;u=f65ca85021691830d3de6ac2ade5d01e3d436950&amp;v=4">@tylerbutler](https://github.com/tylerbutler) that would be a big help, thanks.

@JamieMason I was able to try alpha.9 today; unfortunately it is still hanging when I run `syncpack lint`. There's a repro branch here if it's helpful: https://github.com/tylerbutler/FluidFramework/tree/syncpack-config

**Comment by JamieMason** [comment]
Thanks @tylerbutler I'll get a windows VM set up and work on a fix.

**Comment by JamieMason** [comment]
I've tried syncpack 14.0.0-alpha.18 directly and via `npx syncpack@alpha list` on https://github.com/tylerbutler/FluidFramework/tree/syncpack-config and it ran as expected, this was on a Mac though. 

If you get a chance to check this on Windows it would be a big help, as I've [not been able to get hold of a Windows VM since October 2024](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/).
